CREATE TABLE [prodcopy].[Contact_FanClub]
(
[accountid] [uniqueidentifier] NULL,
[accountidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountrolecode] [int] NULL,
[accountrolecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_addressid] [uniqueidentifier] NULL,
[address1_addresstypecode] [int] NULL,
[address1_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_freighttermscode] [int] NULL,
[address1_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_latitude] [float] NULL,
[address1_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_longitude] [float] NULL,
[address1_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_shippingmethodcode] [int] NULL,
[address1_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_utcoffset] [int] NULL,
[address2_addressid] [uniqueidentifier] NULL,
[address2_addresstypecode] [int] NULL,
[address2_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_freighttermscode] [int] NULL,
[address2_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_latitude] [float] NULL,
[address2_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_longitude] [float] NULL,
[address2_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_shippingmethodcode] [int] NULL,
[address2_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_utcoffset] [int] NULL,
[address3_addressid] [uniqueidentifier] NULL,
[address3_addresstypecode] [int] NULL,
[address3_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_freighttermscode] [int] NULL,
[address3_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_latitude] [float] NULL,
[address3_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_longitude] [float] NULL,
[address3_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_shippingmethodcode] [int] NULL,
[address3_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_utcoffset] [int] NULL,
[aging30] [money] NULL,
[aging30_base] [money] NULL,
[aging60] [money] NULL,
[aging60_base] [money] NULL,
[aging90] [money] NULL,
[aging90_base] [money] NULL,
[altai_address1_state] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_address1stateprovinceid] [uniqueidentifier] NULL,
[altai_address1stateprovinceidname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_address2_state] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_address2stateprovinceid] [uniqueidentifier] NULL,
[altai_address2stateprovinceidname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_billthrudate] [datetime] NULL,
[altai_businessunit] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_canregisterothers] [bit] NULL,
[altai_canregisterothersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizaddress] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizcity] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizcountry] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizfax] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizfederaldistrict] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizfirstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizhousedistrict] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizlastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizphone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizsenatedistrict] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizstate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizstatehouserepresentative] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizstatesenator] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizushouserepresentative] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizussenator1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizussenator2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_capwizzip] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_chapter] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_chapterid] [uniqueidentifier] NULL,
[altai_chapteridname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_copyaddress] [bit] NULL,
[altai_copyaddressname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_corporateaffiliations] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_councilid] [uniqueidentifier] NULL,
[altai_councilidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_currentpoints] [int] NULL,
[altai_currentpositionid] [uniqueidentifier] NULL,
[altai_currentpositionidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_deceased] [bit] NULL,
[altai_deceasedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_district] [int] NULL,
[altai_educationbackground] [int] NULL,
[altai_educationbackgroundname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_emp_occupationid] [uniqueidentifier] NULL,
[altai_emp_occupationidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_enddate] [datetime] NULL,
[altai_ethnicorigin] [int] NULL,
[altai_ethnicoriginname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_expirationdate] [datetime] NULL,
[altai_givingcapacity] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_grassroots] [int] NULL,
[altai_grassrootsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_highestdegree] [int] NULL,
[altai_highestdegreename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_homefax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_honorific] [int] NULL,
[altai_honorificname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_honorifictext] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_housedistrict] [int] NULL,
[altai_housesenate] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_islegislator] [bit] NULL,
[altai_islegislatorname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_ismember] [bit] NULL,
[altai_ismembername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_joindate] [datetime] NULL,
[altai_legacycontactid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_legacyinfo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_legacymemberid] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_legacyuserid] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_legislativearea] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_legislativedistrict] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_maincategory] [int] NULL,
[altai_maincategoryname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_memberid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_membership] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_membershiptypeautoupdated] [bit] NULL,
[altai_membershiptypeautoupdatedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_optionalmemberplusyn] [bit] NULL,
[altai_optionalmemberplusynname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_paidthrudate] [datetime] NULL,
[altai_partyaffiliation] [int] NULL,
[altai_partyaffiliationname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_portalcreatedfrom] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_portalid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_primaryaddressid] [int] NULL,
[altai_primaryaddressidname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_primaryexpertise] [int] NULL,
[altai_primaryexpertisename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_primarymembershiptypeid] [uniqueidentifier] NULL,
[altai_primarymembershiptypeidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_prospectstatus] [int] NULL,
[altai_prospectstatusname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_prospecttype] [int] NULL,
[altai_prospecttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_regionid] [uniqueidentifier] NULL,
[altai_regionidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_renewaldata] [datetime] NULL,
[altai_secondaryaddressid] [int] NULL,
[altai_secondaryaddressidname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_senatedistrict] [int] NULL,
[altai_siteadmin] [bit] NULL,
[altai_siteadminname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_solicitorid] [uniqueidentifier] NULL,
[altai_solicitoridname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_solicitoridyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_sortname] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_source] [int] NULL,
[altai_sourcename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_spousefirstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_spouselastname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_spousemiddlename] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_ssn] [nvarchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_startdate] [datetime] NULL,
[altai_subcategory] [int] NULL,
[altai_subcategoryname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_suffix] [int] NULL,
[altai_suffixname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_suffixtext] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_suspenddate] [datetime] NULL,
[altai_telephone1id] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_telephone2id] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_totalknownwealth] [int] NULL,
[altai_ushousedistrict] [int] NULL,
[altai_ussenatedistrict] [int] NULL,
[altai_validateaddress] [bit] NULL,
[altai_validateaddress1] [bit] NULL,
[altai_validateaddress1date] [datetime] NULL,
[altai_validateaddress1name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_validateaddress2] [bit] NULL,
[altai_validateaddress2date] [datetime] NULL,
[altai_validateaddress2name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_validateaddressname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddresscity] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddresscompany] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddresscountry] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddressdate] [datetime] NULL,
[altai_verifiedaddresserror] [bit] NULL,
[altai_verifiedaddresserrorcode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddresserrormessage] [nvarchar] (225) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddresserrorname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddressline1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddressline2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddressname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddressstate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddresstelephone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_verifiedaddresszip] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_wealthscore] [int] NULL,
[altai_web_donationtype] [int] NULL,
[altai_web_donationtypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_web_text1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_web_text2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_web_text3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_web_text4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_web_text5] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_webcompanyname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_weblogin] [nvarchar] (75) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[altai_webpassword] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[anniversary] [datetime] NULL,
[annualincome] [money] NULL,
[annualincome_base] [money] NULL,
[assistantname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assistantphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthdate] [datetime] NULL,
[business2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[callback] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[childrensnames] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contactid] [uniqueidentifier] NOT NULL,
[createdby] [uniqueidentifier] NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creditlimit] [money] NULL,
[creditlimit_base] [money] NULL,
[creditonhold] [bit] NULL,
[creditonholdname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customersizecode] [int] NULL,
[customersizecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customertypecode] [int] NULL,
[customertypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_activateurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_address1zipplus] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_address2zipplus] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_axorderno] [int] NULL,
[dcm_behaviorscore] [decimal] (28, 0) NULL,
[dcm_cardactivationdate] [datetime] NULL,
[dcm_currentmembership] [uniqueidentifier] NULL,
[dcm_currentmembershipname] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_defaultpricelevelid_lookup] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_ecommerceautorenew] [bit] NULL,
[dcm_ecommerceautorenewname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_ecommerceinvoice] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_ecommercetransid] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_emailscore] [decimal] (28, 0) NULL,
[dcm_eventscore] [decimal] (28, 0) NULL,
[dcm_fanclubbarcode] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_fanclubcardactivated] [bit] NULL,
[dcm_fanclubcardactivatedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_fanclubinfoupdated] [bit] NULL,
[dcm_fanclubinfoupdatedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_fanclubneworrenewal] [bit] NULL,
[dcm_fanclubneworrenewalname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_fanclubnewrenewal] [bit] NULL,
[dcm_fanclubnewrenewalname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_favoritecowboysmerchandise] [int] NULL,
[dcm_favoritecowboysmerchandisename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_favoritecowboysopponent] [int] NULL,
[dcm_favoritecowboysopponentname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_favoritecowboysplayer] [int] NULL,
[dcm_favoritecowboysplayername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_fulfillmenttrackinginfo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_generalcomplaint] [int] NULL,
[dcm_loginissues] [int] NULL,
[dcm_membershippackageprinted] [bit] NULL,
[dcm_membershippackageprintedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_membershippackageshipdate] [datetime] NULL,
[dcm_membershippackagetrackingid] [int] NULL,
[dcm_membersincelookupid] [uniqueidentifier] NULL,
[dcm_membersincelookupidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_membersinceyyyy] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_migration] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_newmembershipcreated] [bit] NULL,
[dcm_newmembershipcreatedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_oldprotechcontactid] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_orderid] [int] NULL,
[dcm_ordernumber] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_ornament] [bit] NULL,
[dcm_ornamentname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_packageshipdate] [datetime] NULL,
[dcm_packagewaitingonshipping] [bit] NULL,
[dcm_packagewaitingonshippingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_primarymembershiprecordid] [uniqueidentifier] NULL,
[dcm_primarymembershiprecordid_lookup] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_primarymembershiprecordidname] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_primarymembershiptypeid_lookup] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_printnewmemberpackage] [bit] NULL,
[dcm_printnewmemberpackagename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_printrenewalmemberpackage] [bit] NULL,
[dcm_printrenewalmemberpackagename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_purpose] [int] NULL,
[dcm_purposename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_replacementcardprintedon] [datetime] NULL,
[dcm_replacementcardrequest] [bit] NULL,
[dcm_replacementcardrequestname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_senttodcm] [bit] NULL,
[dcm_senttodcmdate] [datetime] NULL,
[dcm_senttodcmname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_shippingsatisfaction] [int] NULL,
[dcm_sthaccount] [bit] NULL,
[dcm_sthaccountname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_sthaccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_sthaccounttype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_sthcompany] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_sthservicerep] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_storeid] [uniqueidentifier] NULL,
[dcm_storeid_lookup] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_storeidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_surveyscore] [decimal] (28, 0) NULL,
[dcm_teamperformance] [int] NULL,
[dcm_tickettype] [int] NULL,
[dcm_tickettypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_unique] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_updaterequested] [bit] NULL,
[dcm_updaterequestedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_validaddress] [bit] NULL,
[dcm_validaddressname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_webloginname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_webloginpassword] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_webmembershiprecordid] [uniqueidentifier] NULL,
[dcm_webmembershiprecordidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_websecretanswer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dcm_websecretquestion] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[defaultpricelevelid] [uniqueidentifier] NULL,
[defaultpricelevelidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[department] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkemail] [bit] NULL,
[donotbulkemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkpostalmail] [bit] NULL,
[donotbulkpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotemail] [bit] NULL,
[donotemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotfax] [bit] NULL,
[donotfaxname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotphone] [bit] NULL,
[donotphonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotpostalmail] [bit] NULL,
[donotpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmarketingmaterialname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmm] [bit] NULL,
[educationcode] [int] NULL,
[educationcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employeeid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimage] [varbinary] (max) NULL,
[entityimage_timestamp] [bigint] NULL,
[entityimage_url] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimageid] [uniqueidentifier] NULL,
[exchangerate] [decimal] (28, 0) NULL,
[externaluseridentifier] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[familystatuscode] [int] NULL,
[familystatuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftpsiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fullname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gendercode] [int] NULL,
[gendercodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[governmentid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[haschildrencode] [int] NULL,
[haschildrencodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[importsequencenumber] [int] NULL,
[isbackofficecustomer] [bit] NULL,
[isbackofficecustomername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isprivatename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[jobtitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastusedincampaign] [datetime] NULL,
[leadsourcecode] [int] NULL,
[leadsourcecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managername] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managerphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masterid] [uniqueidentifier] NULL,
[merged] [bit] NULL,
[mergedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middlename] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilephone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nickname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numberofchildren] [int] NULL,
[originatingleadid] [uniqueidentifier] NULL,
[originatingleadidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[originatingleadidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owningbusinessunit] [uniqueidentifier] NULL,
[owningteam] [uniqueidentifier] NULL,
[owninguser] [uniqueidentifier] NULL,
[pager] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactid] [uniqueidentifier] NULL,
[parentcontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomerid] [uniqueidentifier] NULL,
[parentcustomeridname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridyominame] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[participatesinworkflow] [bit] NULL,
[participatesinworkflowname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymenttermscode] [int] NULL,
[paymenttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmentdaycode] [int] NULL,
[preferredappointmentdaycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmenttimecode] [int] NULL,
[preferredappointmenttimecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredcontactmethodcode] [int] NULL,
[preferredcontactmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredequipmentid] [uniqueidentifier] NULL,
[preferredequipmentidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredserviceid] [uniqueidentifier] NULL,
[preferredserviceidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuserid] [uniqueidentifier] NULL,
[preferredsystemuseridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuseridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[processid] [uniqueidentifier] NULL,
[salutation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippingmethodcode] [int] NULL,
[shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spousesname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stageid] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[suffix] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[territorycode] [int] NULL,
[territorycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timezoneruleversionnumber] [int] NULL,
[transactioncurrencyid] [uniqueidentifier] NULL,
[transactioncurrencyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[traversedpath] [nvarchar] (1250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utcconversiontimezonecode] [int] NULL,
[versionnumber] [bigint] NULL,
[websiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomifirstname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomifullname] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomilastname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomimiddlename] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[copyloaddate] [datetime] NULL CONSTRAINT [DF__Contact_F__copyl__4E53A1AA] DEFAULT (getdate())
)
GO
ALTER TABLE [prodcopy].[Contact_FanClub] ADD CONSTRAINT [PK__Contact___7126F91D9CA2B809] PRIMARY KEY CLUSTERED  ([contactid])
GO
