CREATE TABLE [prodcopy].[Contact]
(
[accountid] [uniqueidentifier] NULL,
[accountidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[accountrolecode] [int] NULL,
[accountrolecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_addressid] [uniqueidentifier] NULL,
[address1_addresstypecode] [int] NULL,
[address1_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_freighttermscode] [int] NULL,
[address1_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_latitude] [float] NULL,
[address1_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_longitude] [float] NULL,
[address1_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_shippingmethodcode] [int] NULL,
[address1_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address1_utcoffset] [int] NULL,
[address2_addressid] [uniqueidentifier] NULL,
[address2_addresstypecode] [int] NULL,
[address2_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_freighttermscode] [int] NULL,
[address2_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_latitude] [float] NULL,
[address2_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_longitude] [float] NULL,
[address2_name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_shippingmethodcode] [int] NULL,
[address2_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address2_utcoffset] [int] NULL,
[address3_addressid] [uniqueidentifier] NULL,
[address3_addresstypecode] [int] NULL,
[address3_addresstypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_country] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_county] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_freighttermscode] [int] NULL,
[address3_freighttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_latitude] [float] NULL,
[address3_line1] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_line2] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_line3] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_longitude] [float] NULL,
[address3_name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_postalcode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_postofficebox] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_primarycontactname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_shippingmethodcode] [int] NULL,
[address3_shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_stateorprovince] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_upszone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[address3_utcoffset] [int] NULL,
[aging30] [money] NULL,
[aging30_base] [money] NULL,
[aging60] [money] NULL,
[aging60_base] [money] NULL,
[aging90] [money] NULL,
[aging90_base] [money] NULL,
[anniversary] [datetime] NULL,
[annualincome] [money] NULL,
[annualincome_base] [money] NULL,
[assistantname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assistantphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[birthdate] [datetime] NULL,
[business2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[callback] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_age] [int] NULL,
[cdi_allowtextmessages] [bit] NULL,
[cdi_allowtextmessagesname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_facebook] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_gender] [bit] NULL,
[cdi_gendername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_grade] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_identifiedon] [datetime] NULL,
[cdi_image] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_ip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_latitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_linkedin] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_longitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_partitionkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_rowkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_score] [int] NULL,
[cdi_social] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_taldisplay] [uniqueidentifier] NULL,
[cdi_taldisplayname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_taldonotdisplay] [uniqueidentifier] NULL,
[cdi_taldonotdisplayname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_totalscore] [int] NULL,
[cdi_twitter] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_visitorkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[childrensnames] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[company] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contactid] [uniqueidentifier] NOT NULL,
[createdby] [uniqueidentifier] NULL,
[createdbyexternalparty] [uniqueidentifier] NULL,
[createdbyexternalpartyname] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyexternalpartyyominame] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdon] [datetime] NULL,
[createdonbehalfby] [uniqueidentifier] NULL,
[createdonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[createdonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creditlimit] [money] NULL,
[creditlimit_base] [money] NULL,
[creditonhold] [bit] NULL,
[creditonholdname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customersizecode] [int] NULL,
[customersizecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[customertypecode] [int] NULL,
[customertypecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_2016gamepasscodes] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_2017gamepasscodes] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_abilitecaddresslink] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_abilitecaddresslinkcount] [int] NULL,
[dal_abilitecconsumerlink] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_abilitecconsumerlinkcount] [int] NULL,
[dal_acxmcountryoforigin] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_acxmethnicrollupcode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_acxmlangprefcode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_acxmreligiouscode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_customereventid] [uniqueidentifier] NULL,
[dal_customereventidname] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_dcuelitemember] [bit] NULL,
[dal_dcuelitemembername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_emailcowboysclub] [bit] NULL,
[dal_emailcowboysclubname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_emailstadiumclub] [bit] NULL,
[dal_emailstadiumclubname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_endtime] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_firstnamelegal] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_holidayphoto] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_jasontempflag] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_jkresponse] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_jktotalattendees] [int] NULL,
[dal_jkyearinvited] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_lastnamelegal] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_lastpglyear] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_lastrakdate] [datetime] NULL,
[dal_lastrrdate] [datetime] NULL,
[dal_lasttouchpointdate] [datetime] NULL,
[dal_lasttp] [datetime] NULL,
[dal_laurentempflag] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_lcottempfield] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_matchtomerchlist] [bit] NULL,
[dal_matchtomerchlistname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_multiyearpglbuyer] [bit] NULL,
[dal_multiyearpglbuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_oilgasindustry] [bit] NULL,
[dal_oilgasindustryname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ostempflag] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_paperless] [bit] NULL,
[dal_paperlessname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_paperlesstickets] [bit] NULL,
[dal_paperlessticketsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_pepatempflag] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_personicxcluster] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_pgleventdate] [datetime] NULL,
[dal_pgleventlocation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_pglsalesperson] [uniqueidentifier] NULL,
[dal_pglsalespersonname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_pglsalespersonyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_photogroupsize] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_photolocation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_phototime] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_playoffpayment] [bit] NULL,
[dal_playoffpaymentname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_relatedcontactid] [uniqueidentifier] NULL,
[dal_relatedcontactidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_shoprunnerpin] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_srv_attribute] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_srv_attributescore] [int] NULL,
[dal_srv_comment] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_srv_overallsat] [int] NULL,
[dal_sthtixcollectioncolorcode] [int] NULL,
[dal_sthtixcollectioncolorcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_surveynflgameday] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_surveysthexperience] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[defaultpricelevelid] [uniqueidentifier] NULL,
[defaultpricelevelidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[department] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkemail] [bit] NULL,
[donotbulkemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotbulkpostalmail] [bit] NULL,
[donotbulkpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotemail] [bit] NULL,
[donotemailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotfax] [bit] NULL,
[donotfaxname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotphone] [bit] NULL,
[donotphonename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotpostalmail] [bit] NULL,
[donotpostalmailname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmarketingmaterialname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[donotsendmm] [bit] NULL,
[educationcode] [int] NULL,
[educationcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[emailaddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[employeeid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimage] [varbinary] (max) NULL,
[entityimage_timestamp] [bigint] NULL,
[entityimage_url] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[entityimageid] [uniqueidentifier] NULL,
[et_lastbouncetype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[exchangerate] [decimal] (28, 0) NULL,
[externaluseridentifier] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[familystatuscode] [int] NULL,
[familystatuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftpsiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fullname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gendercode] [int] NULL,
[gendercodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[governmentid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[haschildrencode] [int] NULL,
[haschildrencodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[home2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[importsequencenumber] [int] NULL,
[isbackofficecustomer] [bit] NULL,
[isbackofficecustomername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[isprivatename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[jobtitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastonholdtime] [datetime] NULL,
[lastusedincampaign] [datetime] NULL,
[leadsourcecode] [int] NULL,
[leadsourcecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managername] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[managerphone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mastercontactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[masterid] [uniqueidentifier] NULL,
[merged] [bit] NULL,
[mergedname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[middlename] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mobilephone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedby] [uniqueidentifier] NULL,
[modifiedbyexternalparty] [uniqueidentifier] NULL,
[modifiedbyexternalpartyname] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyexternalpartyyominame] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedon] [datetime] NULL,
[modifiedonbehalfby] [uniqueidentifier] NULL,
[modifiedonbehalfbyname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[modifiedonbehalfbyyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_monthlyerreportsenderid] [uniqueidentifier] NULL,
[new_monthlyerreportsenderidname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_monthlyerreportsenderidyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[nickname] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[numberofchildren] [int] NULL,
[onholdtime] [int] NULL,
[originatingleadid] [uniqueidentifier] NULL,
[originatingleadidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[originatingleadidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[overriddencreatedon] [datetime] NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owneridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owningbusinessunit] [uniqueidentifier] NULL,
[owningteam] [uniqueidentifier] NULL,
[owninguser] [uniqueidentifier] NULL,
[pager] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactid] [uniqueidentifier] NULL,
[parentcontactidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcontactidyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomerid] [uniqueidentifier] NULL,
[parentcustomeridname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridtype] [nvarchar] (64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[parentcustomeridyominame] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[participatesinworkflow] [bit] NULL,
[participatesinworkflowname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[paymenttermscode] [int] NULL,
[paymenttermscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmentdaycode] [int] NULL,
[preferredappointmentdaycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredappointmenttimecode] [int] NULL,
[preferredappointmenttimecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredcontactmethodcode] [int] NULL,
[preferredcontactmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredequipmentid] [uniqueidentifier] NULL,
[preferredequipmentidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredserviceid] [uniqueidentifier] NULL,
[preferredserviceidname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuserid] [uniqueidentifier] NULL,
[preferredsystemuseridname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[preferredsystemuseridyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[processid] [uniqueidentifier] NULL,
[salutation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[shippingmethodcode] [int] NULL,
[shippingmethodcodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[slaid] [uniqueidentifier] NULL,
[slainvokedid] [uniqueidentifier] NULL,
[slainvokedidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[slaname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[spousesname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[stageid] [uniqueidentifier] NULL,
[statecode] [int] NULL,
[statecodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[statuscode] [int] NULL,
[statuscodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_agerange] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_allspendtotal] [money] NULL,
[str_allspendtotal_base] [money] NULL,
[str_casesource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_casestatus] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_casesubject] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_casetype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_category] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_cegradescore] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientassistantemail] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientassistantname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientassistantphone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientbeconfidencescore] [decimal] (28, 0) NULL,
[str_clientbegradeticketprice] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientbegradetotalspend] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientbescoreticketprice] [decimal] (28, 0) NULL,
[str_clientbescoretotalspend] [decimal] (28, 0) NULL,
[str_clientbirthdayadjusted] [datetime] NULL,
[str_clientceconfidencescore] [decimal] (28, 0) NULL,
[str_clientceprospectscore] [decimal] (28, 0) NULL,
[str_clientcrmsalescontest1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientdayssincelastactivity] [int] NULL,
[str_clientemailsthclub] [bit] NULL,
[str_clientemailsthclubname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientemailsthfaa] [bit] NULL,
[str_clientemailsthfaaname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientemailsthlegends] [bit] NULL,
[str_clientemailsthlegendsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientemailsthnonoption] [bit] NULL,
[str_clientemailsthnonoptionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientemailsthowners] [bit] NULL,
[str_clientemailsthownersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientemailsthreserve] [bit] NULL,
[str_clientemailsthreservename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientemailsuitelegends] [bit] NULL,
[str_clientemailsuitelegendsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientemailsuiteowners] [bit] NULL,
[str_clientemailsuiteownersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientemailsuiteregular] [bit] NULL,
[str_clientemailsuiteregularname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientemploymentsize] [decimal] (28, 0) NULL,
[str_clientgeorgestraitpwclub] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientgeorgestraitpwreserve] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientgeorgestraitpwsuiteclub] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientgeorgestraitpwsuitereserve] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientheadline] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientheavyfacebookuser] [int] NULL,
[str_clientheavylinkedinuser] [int] NULL,
[str_clientheavytwitteruser] [int] NULL,
[str_clientjktempflag] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientliveanalyticsid] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientmerchtrackingnumber] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientmobilesocialnetworkuser] [int] NULL,
[str_clientnflgamerewindoffercode] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientpasswords] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientpersonicxclustername] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientpersonicxconfidencescore] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientpgl2009] [bit] NULL,
[str_clientpgl2009name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientpgl2010] [bit] NULL,
[str_clientpgl2010name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientpgl2012] [bit] NULL,
[str_clientpgl2012name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientpgl2013] [bit] NULL,
[str_clientpgl2013name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientrenewalriskconfidence] [decimal] (28, 0) NULL,
[str_clientrenewalriskconfidence2] [decimal] (28, 0) NULL,
[str_clientrenewalriskconfidence25] [decimal] (28, 0) NULL,
[str_clientrenewalriskconfidence3] [decimal] (28, 0) NULL,
[str_clientrenewalriskscore] [decimal] (28, 0) NULL,
[str_clientrenewalriskscore2] [decimal] (28, 0) NULL,
[str_clientrenewalriskscore25] [decimal] (28, 0) NULL,
[str_clientrenewalriskscore3] [decimal] (28, 0) NULL,
[str_clientsalesvolume] [decimal] (28, 0) NULL,
[str_clientsiccode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientsiccodedescription] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientsocialinfluencer] [int] NULL,
[str_clientsociallyinfluenced] [int] NULL,
[str_clientsource] [int] NULL,
[str_clientsourcename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientsuitecontractdate] [datetime] NULL,
[str_clientteflag] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientticketexchangeaveragespend] [decimal] (28, 0) NULL,
[str_clientticketexchangetotalseats] [decimal] (28, 0) NULL,
[str_clientticketexchangetotalspend] [decimal] (28, 0) NULL,
[str_clienttype] [int] NULL,
[str_clienttypename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientweboatowner] [bit] NULL,
[str_clientweboatownername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientweincome] [int] NULL,
[str_clientwenetworth] [int] NULL,
[str_clientweplaneowner] [bit] NULL,
[str_clientweplaneownername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientwepricecode] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_clientwerealestatevalue] [int] NULL,
[str_college] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_concertinterests] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_doornameplate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_dwcompanies] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_dwduplicate] [bit] NULL,
[str_dwduplicatename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_dwid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_dwmodifiedon] [datetime] NULL,
[str_externalcapacitymodel] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalclustername] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_externalprioritymodel] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_facebookhandle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoritebeverage] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoritedestination] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoriteflower] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoriteopponent] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoriteplayer] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoriterestaurant] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_favoriteteam] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_hobbies] [nvarchar] (350) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_hometown] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_householdincome] [money] NULL,
[str_householdincome_base] [money] NULL,
[str_id] [int] NULL,
[str_idtext] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_instagramhandle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_jksuiteadmin] [nvarchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_jonesinvitelist] [bit] NULL,
[str_jonesinvitelistname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_lastactivitydate] [datetime] NULL,
[str_legendsservicepersonid] [uniqueidentifier] NULL,
[str_legendsservicepersonidname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_legendsservicepersonidyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_marketingcontactindustryid] [uniqueidentifier] NULL,
[str_marketingcontactindustryidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_marketingcontactsourceid] [uniqueidentifier] NULL,
[str_marketingcontactsourceidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_marketingcontacttypeid] [uniqueidentifier] NULL,
[str_marketingcontacttypeidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_musicclassical] [bit] NULL,
[str_musicclassicalname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_musiccountry] [bit] NULL,
[str_musiccountryname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_musicpop] [bit] NULL,
[str_musicpopname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_musicrap] [bit] NULL,
[str_musicrapname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_musicrock] [bit] NULL,
[str_musicrockname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_neglectmeter] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_neglectreason] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_nextactivitydate] [datetime] NULL,
[str_nextactivitysubject] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_number] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_openactivitycount] [int] NULL,
[str_openticketcase] [bit] NULL,
[str_openticketcasename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_openticketopportunity] [bit] NULL,
[str_openticketopportunityname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_oppdaysinstage] [int] NULL,
[str_oppproduct] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_oppsource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_oppstage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_opptagcount] [int] NULL,
[str_otherinformation] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_parkingspotnumber] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_partnerid] [uniqueidentifier] NULL,
[str_partneridname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_partneridyominame] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_premiumtype] [uniqueidentifier] NULL,
[str_premiumtypename] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_priority] [int] NULL,
[str_rating] [int] NULL,
[str_ratingname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_score] [int] NULL,
[str_search] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_select] [bit] NULL,
[str_selectname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_serviceperson] [uniqueidentifier] NULL,
[str_servicepersonname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_servicepersonyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_shirtsize] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_shoesize] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_showsfamily] [bit] NULL,
[str_showsfamilyname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_since] [datetime] NULL,
[str_source] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_sportsinterests] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_suiteid] [uniqueidentifier] NULL,
[str_suiteidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_suiteservicepersonid] [uniqueidentifier] NULL,
[str_suiteservicepersonidname] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_suiteservicepersonidyominame] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_ticketeventtotalall] [int] NULL,
[str_ticketeventtotalarena] [int] NULL,
[str_ticketeventtotallast] [int] NULL,
[str_ticketeventtotalthis] [int] NULL,
[str_ticketnumberaverageall] [decimal] (28, 0) NULL,
[str_ticketnumberaveragearena] [decimal] (28, 0) NULL,
[str_ticketnumberaveragelast] [decimal] (28, 0) NULL,
[str_ticketnumberaveragethis] [decimal] (28, 0) NULL,
[str_ticketnumbertotalall] [int] NULL,
[str_ticketnumbertotalarena] [int] NULL,
[str_ticketnumbertotallast] [int] NULL,
[str_ticketnumbertotalthis] [int] NULL,
[str_ticketpriceaverageall] [money] NULL,
[str_ticketpriceaverageall_base] [money] NULL,
[str_ticketpriceaveragearena] [money] NULL,
[str_ticketpriceaveragearena_base] [money] NULL,
[str_ticketpriceaveragelast] [money] NULL,
[str_ticketpriceaveragelast_base] [money] NULL,
[str_ticketpriceaveragethis] [money] NULL,
[str_ticketpriceaveragethis_base] [money] NULL,
[str_ticketspendaverageall] [money] NULL,
[str_ticketspendaverageall_base] [money] NULL,
[str_ticketspendaveragearena] [money] NULL,
[str_ticketspendaveragearena_base] [money] NULL,
[str_ticketspendaveragelast] [money] NULL,
[str_ticketspendaveragelast_base] [money] NULL,
[str_ticketspendaveragethis] [money] NULL,
[str_ticketspendaveragethis_base] [money] NULL,
[str_ticketspendtotalall] [money] NULL,
[str_ticketspendtotalall_base] [money] NULL,
[str_ticketspendtotalarena] [money] NULL,
[str_ticketspendtotalarena_base] [money] NULL,
[str_ticketspendtotallast] [money] NULL,
[str_ticketspendtotallast_base] [money] NULL,
[str_ticketspendtotalthis] [money] NULL,
[str_ticketspendtotalthis_base] [money] NULL,
[str_tvname] [nvarchar] (27) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_twitterhandle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[str_wheelstop] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[suffix] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[territorycode] [int] NULL,
[territorycodename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[timezoneruleversionnumber] [int] NULL,
[transactioncurrencyid] [uniqueidentifier] NULL,
[transactioncurrencyidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[traversedpath] [nvarchar] (1250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[utcconversiontimezonecode] [int] NULL,
[versionnumber] [bigint] NULL,
[websiteurl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomifirstname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomifullname] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomilastname] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[yomimiddlename] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[copyloaddate] [datetime] NULL CONSTRAINT [DF__Contact__copyloa__17036CC0] DEFAULT (getdate()),
[new_ssbcrmsystemSSIDWinner] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssbcrmsystemSSIDWinnerSourceSystem] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssbcrmsystemdimcustomerids] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssbcrmsystemacctid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssbcrmsystemcontactid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ticketstotalseats] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ticketspreviousyearmodified] [datetime] NULL,
[dal_ticketingterminationdate] [datetime] NULL,
[dal_ssb_suiteregularname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_suiteregular] [bit] NULL,
[dal_ssb_suiteownersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_suiteowners] [bit] NULL,
[dal_ssb_suitelegendsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_suitelegends] [bit] NULL,
[dal_ssb_sthreservename] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_sthreserve] [bit] NULL,
[dal_ssb_sthownersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_sthowners] [bit] NULL,
[dal_ssb_sthnonoptionname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_sthnonoption] [bit] NULL,
[dal_ssb_sthlegendsname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_sthlegends] [bit] NULL,
[dal_ssb_sthfoundersname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_sthfounders] [bit] NULL,
[dal_ssb_sthclubname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_sthclub] [bit] NULL,
[dal_ssb_stadiumclubname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_stadiumclub] [bit] NULL,
[dal_ssb_secondarysellername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_secondaryseller] [bit] NULL,
[dal_ssb_secondarymarket] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_secondarybuyername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_secondarybuyer] [bit] NULL,
[dal_ssb_seatgeekserviceperson] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_seatgeeksalesperson] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_seatgeekaccountid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_pglothername] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_pglother] [bit] NULL,
[dal_ssb_pglcowboysname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_pglcowboys] [bit] NULL,
[dal_ssb_personicxcluster] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_cowboysfitname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_cowboysfit] [bit] NULL,
[dal_ssb_cowboysclubname] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_cowboysclub] [bit] NULL,
[dal_ssb_additionalinfo5] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_additionalinfo4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_additionalinfo3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_additionalinfo2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_ssb_additionalinfo1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_lastyearmodified] [datetime] NULL,
[dal_email_mergeaddr3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_email_mergeaddr2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_email_mergeaddr1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_lasttouchpointtype] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_waitlistpgleventid] [uniqueidentifier] NULL,
[dal_waitlistpgleventidname] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_ssb_fanclub] [decimal] (28, 0) NULL,
[new_ssb_spend12months_cowboysevents] [decimal] (28, 0) NULL,
[new_ssb_spend12months_merch] [decimal] (28, 0) NULL,
[new_ssb_spend12months_noncowboysevents] [decimal] (28, 0) NULL,
[new_ssb_youthcamps] [decimal] (28, 0) NULL,
[new_ssbprimaryseatgeekid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dal_sgglobalid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [prodcopy].[Contact] ADD CONSTRAINT [PK__Contact__7126F91DB8FCBF74] PRIMARY KEY CLUSTERED  ([contactid])
GO
